name: Secure Build and Keyless Sign

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  packages: write
  id-token: write

env:
  IMAGE_NAME: ghcr.io/iheb-mrabet/cloud-pipeline-compromise/vulnerable-flask-app

jobs:
  build-sign:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install cosign
        uses: sigstore/cosign-installer@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build image
        run: |
          docker build -t $IMAGE_NAME:${{ github.sha }} ./app

      - name: Push image
        run: |
          docker push $IMAGE_NAME:${{ github.sha }}

      - name: Get image digest
        id: digest
        run: |
          DIGEST=$(docker inspect --format='{{index .RepoDigests 0}}' $IMAGE_NAME:${{ github.sha }})
          echo "digest=$DIGEST" >> $GITHUB_OUTPUT
          echo "Image digest: $DIGEST"

      - name: Keyless sign image
        run: |
          cosign sign --yes ${{ steps.digest.outputs.digest }}

      - name: Verify keyless signature
        run: |
          cosign verify \
            --certificate-identity-regexp "https://github.com/iheb-mrabet/cloud-pipeline-compromise/.github/workflows/secure-build-sign.yml@refs/heads/main" \
            --certificate-oidc-issuer "https://token.actions.githubusercontent.com" \
            ${{ steps.digest.outputs.digest }}
